// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package store

import (
	"time"
)

type User struct {
	ID            int64     `db:"id" json:"id"`
	Code          string    `db:"code" json:"code"`
	FullName      string    `db:"full_name" json:"full_name"`
	Email         string    `db:"email" json:"email"`
	PhoneNumber   string    `db:"phone_number" json:"phone_number"`
	Password      string    `db:"password" json:"password"`
	Salt          string    `db:"salt" json:"salt"`
	IsVerifyPhone bool      `db:"is_verify_phone" json:"is_verify_phone"`
	IsVerifyEmail bool      `db:"is_verify_email" json:"is_verify_email"`
	CreatedAt     time.Time `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time `db:"updated_at" json:"updated_at"`
}
