// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: user_message.proto

package home_servicesv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UserHealthzRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UserHealthzRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserHealthzRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserHealthzRequestMultiError, or nil if none found.
func (m *UserHealthzRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UserHealthzRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UserHealthzRequestMultiError(errors)
	}

	return nil
}

// UserHealthzRequestMultiError is an error wrapping multiple validation errors
// returned by UserHealthzRequest.ValidateAll() if the designated constraints
// aren't met.
type UserHealthzRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserHealthzRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserHealthzRequestMultiError) AllErrors() []error { return m }

// UserHealthzRequestValidationError is the validation error returned by
// UserHealthzRequest.Validate if the designated constraints aren't met.
type UserHealthzRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserHealthzRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserHealthzRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserHealthzRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserHealthzRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserHealthzRequestValidationError) ErrorName() string {
	return "UserHealthzRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UserHealthzRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserHealthzRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserHealthzRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserHealthzRequestValidationError{}

// Validate checks the field values on UserHealthzResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UserHealthzResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserHealthzResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserHealthzResponseMultiError, or nil if none found.
func (m *UserHealthzResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UserHealthzResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return UserHealthzResponseMultiError(errors)
	}

	return nil
}

// UserHealthzResponseMultiError is an error wrapping multiple validation
// errors returned by UserHealthzResponse.ValidateAll() if the designated
// constraints aren't met.
type UserHealthzResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserHealthzResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserHealthzResponseMultiError) AllErrors() []error { return m }

// UserHealthzResponseValidationError is the validation error returned by
// UserHealthzResponse.Validate if the designated constraints aren't met.
type UserHealthzResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserHealthzResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserHealthzResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserHealthzResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserHealthzResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserHealthzResponseValidationError) ErrorName() string {
	return "UserHealthzResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UserHealthzResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserHealthzResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserHealthzResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserHealthzResponseValidationError{}
